"""Prompt templates for the agent."""

from agent.prompts.evaluate import (
    EVALUATE_SYSTEM_PROMPT,
    EVALUATE_USER_PROMPT_TEMPLATE,
)
from agent.prompts.translate import (
    TRANSLATE_FEEDBACK_SECTION,
    TRANSLATE_SYSTEM_PROMPT,
    TRANSLATE_USER_PROMPT_TEMPLATE,
)

__all__ = [
    "EVALUATE_SYSTEM_PROMPT",
    "EVALUATE_USER_PROMPT_TEMPLATE",
    "TRANSLATE_FEEDBACK_SECTION",
    "TRANSLATE_SYSTEM_PROMPT",
    "TRANSLATE_USER_PROMPT_TEMPLATE",
]
